name: IDENOVO
favicon: null
layout_spectrum: 0.8446572301909328
typography_spectrum: 0.24511572089977562
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.4201656763907522
  lightness: 0.38558369455859065
  saturation: 0.020962406182661653
  rhythmicContrast: 0.8403029588516802
purpose: []
